repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: bash -c 'source .venv/bin/activate && ruff format --line-length 79 src/'
        language: system
        types: [python]

      - id: ruff
        name: ruff
        entry: bash -c 'source .venv/bin/activate && ruff check src/ --select=E,F,I,B,UP,SIM,PERF --fix --line-length 79'
        language: system
        types: [python]

      - id: pyright
        name: pyright
        entry: bash -c 'source .venv/bin/activate && pyright src/'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
