repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-format
        name: ruff format
        files: ^src/

      - id: ruff
        name: ruff check
        files: ^src/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit security check
        args: ["-c", "pyproject.toml"]
        files: ^src/
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        name: pyright type-check
        files: ^src/
        pass_filenames: false
        always_run: true
        additional_dependencies:
          [
            "aiogram==3.22.0",
            "alembic==1.17.0",
            "asyncpg==0.30.0",
            "dependency-injector==4.48.2",
            "fastapi==0.116.1",
            "psycopg2-binary==2.9.11",
            "pydantic-settings==2.11.0",
            "pyjwt==2.10.1",
            "scalar-fastapi==1.4.3",
            "slowapi==0.1.9",
            "sqlalchemy==2.0.41",
            "uvicorn==0.38.0",
          ]
