name: Pyright

on:
  push:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pyright
        run: |
          python -m pip install --upgrade pip
          pip install pyright
      - name: Run pyright
        run: |
          pyright src/
